project:
  type: website
  resources:
    - mis_reportes/Reporte-modulo5.pdf

website:
  title: "Transición hacia Energías Renovables"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Bases de datos"
        href: mis_reportes/bases_de_datos.qmd
      - text: "Reporte"
        href: mis_reportes/reporte.qmd
      - text: "Dashboard"
        href: mis_reportes/dashboard.qmd
      - text: "Repositorio"
        href: https://github.com/AxelEduardoAlvaradoArce/Proyecto_Energias_Renovables

format:
  html:
    theme: minty
    toc: true
    lang: es
