project:
  type: website
  render:
    - "**/*.qmd"
  resources:
    - mis_reportes/Dashboard_Energias_Renovables.html
    - mis_reportes/analisis_notebook.html
    - mis_reportes/Proyecto_Energias_Analisis.ipynb

website:
  title: "Transición hacia Energías Renovables"
  navbar:
    background: "#285943"      # verde oscuro
    foreground: "#FFFFFF"      # texto blanco
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Bases de datos"
        href: mis_reportes/bases_de_datos.qmd
      - text: "Reporte"
        href: mis_reportes/reporte.qmd
      - text: "Análisis"
        href: mis_reportes/analisis.qmd
      - text: "Dashboard"
        href: mis_reportes/Dashboard_Energias_Renovables.html
      - text: "Repositorio"
        href: https://github.com/AxelEduardoAlvaradoArce/Proyecto_Equipo2

format:
  html:
    theme: [flatly, estilos.scss]
    toc: true
    lang: es
