project:
  type: website
  render:
    - "**/*.qmd"
  resources:
    - mis_reportes/Proyecto_M8_DIACD_Dash_V1.html

website:
  title: "Transición hacia Energías Renovables"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Bases de datos"
        href: mis_reportes/bases_de_datos.qmd
      - text: "Reporte"
        href: mis_reportes/reporte.qmd
      - text: "Dashboard"
        href: mis_reportes/Proyecto_M8_DIACD_Dash_V1.html
      - text: "Repositorio"
        href: https://github.com/AxelEduardoAlvaradoArce/Proyecto_Energias_Renovables

format:
  html:
    theme: [flatly, estilos.scss]
    toc: true
    lang: es
