---
title: "Dashboard Energía y Desarrollo"
author: "Equipo 2" 
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(DT)
library(scales)
library(htmltools)

#colores 
verde_oscuro  <- "#285943"
verde_medio   <- "#5B8E72"
verde_claro   <- "#A8C9B5"
verde_suave   <- "#DDEDE3"

gris_texto    <- "#34403A"
gris_claro    <- "#F5F7F5"
blanco        <- "#FFFFFF"
```

```{r datos, include=FALSE}

url <- "https://raw.githubusercontent.com/AxelEduardoAlvaradoArce/Proyecto_Energias_Renovables/refs/heads/main/datos.csv"
datos <- read.csv(url)

```

```{r pagina_1, include=FALSE}

anio <- 2025
datos_2025 <- datos %>%
  filter(year == anio)

datos_2025 <- datos_2025 %>%
  mutate(
    penetracion_ren = if_else(
      gen_twh > 0,
      ren_twh / gen_twh * 100,
      NA_real_
    )
  )

total_generacion <- sum(
  datos_2025$gen_twh,
  na.rm = TRUE
)

total_renovable <- sum(
  datos_2025$ren_twh,
  na.rm = TRUE
)

promedio_penetracion <- mean(
  datos_2025$penetracion_ren,
  na.rm = TRUE
)

penetracion_global <- 
  total_renovable / total_generacion * 100

numero_paises <- n_distinct(datos_2025$iso3)

#Grafica top 10 e info TOP 3 

top10 <- datos_2025 %>%
  filter(!is.na(penetracion_ren)) %>%
  arrange(desc(penetracion_ren)) %>%
  slice_head(n = 10) %>%
  mutate(
    country = fct_reorder(country, penetracion_ren)
  )

top3 <- top10 %>%
  slice_head(n = 3)

#Tabla por continnetes
resumen_continente <- datos_2025 %>%
  group_by(continente) %>%
  summarise(
    
    energia_promedio = mean(
      tes_gj,
      na.rm = TRUE
    ),
    
    renovable_total = sum(
      ren_twh,
      na.rm = TRUE
    ),
    
    generacion_total = sum(
      gen_twh,
      na.rm = TRUE
    ),
    
    penetracion = 
      renovable_total /
      generacion_total * 100,
    
    numero_paises = n_distinct(iso3),
    
    pib_promedio = mean(
      pib_pc_ppp,
      na.rm = TRUE
    ),
    
    .groups = "drop"
  )

#Formatea la tabla 
tabla_continentes <- resumen_continente %>%
  transmute(
    Continente = continente,
    `Suministro energético per cápita (GJ promedio)` =
      number(energia_promedio, accuracy = 1, big.mark = ","),
    
    `Renovables (TWh)` =
      number(renovable_total, accuracy = 0.1, big.mark = ","),
    
    `Penetración renovable (%)` =
      paste0(round(penetracion, 1), "%"),
    
    `Países` = numero_paises,
    
    `PIB pc PPP promedio` =
      paste0(
        "$",
        number(
          pib_promedio,
          accuracy = 1,
          big.mark = ","
        )
      )
  )

```

Panorama general
=====================================

Row {data-height=150}
-------------------------------------
### Generación eléctrica total
```{r}
valueBox(
  value = paste0(
    number(total_generacion, accuracy = 0.1, big.mark = ","),
    " TWh"
  ),
  caption = "Generación eléctrica total",
  color = "success",
  icon = "fa-bolt"
)
```

### Generación renovable 
```{r}
valueBox(
  value = paste0(
    number(total_renovable, accuracy = 0.1, big.mark = ","),
    " TWh"
  ),
  caption = "Generación renovable",
  color = "success",
  icon = "fa-leaf"
)
```

### Penetración renovable promedio
```{r}
valueBox(
  value = paste0(
    number(promedio_penetracion, accuracy = 0.1),
    "%"
  ),
  caption = "Promedio entre países",
  color = "success",
  icon = "fa-percent"
)
```

### Participación renovable global
```{r}
valueBox(
  value = paste0(
    number(penetracion_global, accuracy = 0.1),
    "%"
  ),
  caption = "Renovables / generación total",
  color = "success",
  icon = "fa-globe"
)
```


Row {data-height=550}
-------------------------------------

### Ranking mundial
```{r}
plot_ly(
  data = top10,
  x = ~penetracion_ren,
  y = ~country,
  type = "bar",
  orientation = "h",
  marker = list(
    color = verde_medio
  ),
  text = ~paste0(
    round(penetracion_ren, 1),
    "%"
  ),
  textposition = "outside",
  hovertemplate = paste(
    "<b>%{y}</b><br>",
    "Penetración renovable: %{x:.1f}%",
    "<extra></extra>"
  )
) %>%
  layout(
    xaxis = list(
      title = "Penetración renovable (%)",
      ticksuffix = "%"
    ),
    yaxis = list(
      title = ""
    ),
    margin = list(
      l = 120,
      r = 40,
      t = 20,
      b = 50
    ),
    plot_bgcolor = blanco,
    paper_bgcolor = blanco
  )

```
  
### Top 3
```{r}
#Tarjeta HTML 

tarjeta_pais <- function(fila, posicion) {
  
  HTML(
    paste0(
      "<div style='
        background:#DDEDE3;
        border-left:6px solid #285943;
        border-radius:10px;
        padding:15px;
        margin-bottom:12px;
      '>",
      
      "<h4 style='margin-top:0;color:#285943;'>",
      "#", posicion, " ", fila$country,
      "</h4>",
      
      "<b>Continente:</b> ", fila$continente, "<br>",
      "<b>Penetración renovable:</b> ",
      round(fila$penetracion_ren, 1), "%<br>",
      "<b>Generación renovable:</b> ",
      number(fila$ren_twh, accuracy = 0.1, big.mark = ","),
      " TWh<br>",
      "<b>Generación eléctrica:</b> ",
      number(fila$gen_twh, accuracy = 0.1, big.mark = ","),
      " TWh<br>",
      "<b>PIB per cápita PPP:</b> $",
      number(fila$pib_pc_ppp, accuracy = 1, big.mark = ","),
      
      "</div>"
    )
  )
}

tarjeta_pais(top3[1, ], 1)
tarjeta_pais(top3[2, ], 2)
tarjeta_pais(top3[3, ], 3)

```

Row {data-height=400}
-------------------------------------
### Vision Continental
```{r} 
#tabla 
datatable(
  tabla_continentes,
  rownames = FALSE,
  options = list(
    pageLength = 10,
    dom = "t",
    autoWidth = TRUE
  )
) %>%
  formatStyle(
    columns = names(tabla_continentes),
    fontSize = "13px"
  )
``` 
### Mapa mundial 2025
```{r}

mapa_paises <- datos_2025 %>%
  select(
    iso3,
    country,
    continente,
    penetracion_ren,
    ren_twh,
    gen_twh
  )

mapa_con_datos <- mapa_paises %>%
  filter(!is.na(penetracion_ren))

mapa_sin_datos <- mapa_paises %>%
  filter(is.na(penetracion_ren))

plot_ly(
  data = mapa_con_datos,
  type = "choropleth",
  locations = ~iso3,
  locationmode = "ISO-3",
  z = ~penetracion_ren,
  
  text = ~paste0(
    "<b>", country, "</b>",
    "<br>Continente: ", continente,
    "<br>Penetración renovable: ",
    round(penetracion_ren, 1), "%",
    "<br>Generación renovable: ",
    scales::number(ren_twh, accuracy = 0.1, big.mark = ","),
    " TWh",
    "<br>Generación eléctrica: ",
    scales::number(gen_twh, accuracy = 0.1, big.mark = ","),
    " TWh"
  ),
  
  hoverinfo = "text",
  
  colorscale = list(
    c(0.00, verde_suave),
    c(0.35, verde_claro),
    c(0.70, verde_medio),
    c(1.00, verde_oscuro)
  ),
  
  zmin = 0,
  zmax = 100,
  
  marker = list(
    line = list(
      color = "#FFFFFF",
      width = 0.5
    )
  ),
  
  colorbar = list(
    title = "Penetración<br>renovable (%)"
  )
  
) %>%
  
  layout(
    geo = list(
      scope = "world",
      showframe = FALSE,
      showcoastlines = TRUE,
      coastlinecolor = "#FFFFFF",
      showcountries = TRUE,
      countrycolor = "#FFFFFF",
      showland = TRUE,
      landcolor = "#D9D9D9",
      projection = list(
        type = "natural earth"
      )
    ),
    
    plot_bgcolor = "#FFFFFF",
    paper_bgcolor = "#FFFFFF",
    
    margin = list(
      l = 0,
      r = 0,
      t = 10,
      b = 0
    )
  )

```
